### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by shin-migami** [TuhinKundu/CSE-2015-19-website#4]
A License with terms -
- No Commercial Use
- Any Content of the Website(as in names, links, pics) can only be used with permission from the author.

I think Creative Commons License would do the job ??

**Comment by Lionex** [comment]
Creative Commons works best for certain types of creative products and intellectual property, like photographs, video, 3D models, but not software.

How do you want people to use the software?

**Comment by shin-migami** [comment]
I just want to put restrictions on content ie others can't use the information like pictures and links but are free to use the design. Please suggest.

**Comment by Lionex** [comment]
Based on the information [here](https://wiki.creativecommons.org/wiki/Considerations_for_licensors_and_licensees) what you want seems to fall in a gray area as far as CC licensing.  

It seems like you don't actually want to use a CC license though, because some CC licenses require attribution of the source material, but not permission from the content creator.  (At least that's what I saw after skimming.)  

And as for prohibiting commercial use of the _software_, since you have the full copyright to the content you create you can already decide who uses what how.  

I'm not a lawyer so I'm not sure exactly how to write a `LICENSE` file with the permissions you want, but you may have good results just finding a license agreement that does what you want and copying the spirit of the agreement.

**Comment by somnathrakshit** [comment]
Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International should do the trick, I guess.
